image: Visual Studio 2017

matrix:
  fast_finish: true

platform:
- x64

# http://www.appveyor.com/docs/installed-software
environment:
  APPVEYOR_RDP_PASSWORD: 7bKajQWvq4uhfpvc!
  BOOSTDIR: C:\Libraries\boost_1_67_0
  PYTHONDIR: C:\Python36-x64
  QTDIR: "C:\\Qt\\5.9\\msvc2017_64"
  PATH: "%QTDIR%\\bin;%PYTHONDIR%;%PYTHONDIR%\\Scripts;%PATH%"
  PYTHONPATH: "%PYTHONDIR%;%PYTHONDIR%\\Lib;%PYTHONDIR%\\Lib\\site-packages;%PYTHONDIR%\\DLLs"
build:
  parallel: true

init:  
- echo "BornAgain init" %CD% 
- echo %PATH%
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- git submodule -q update --init
  
before_build:
- echo "BornAgain before_build" %CD% 
- python -m pip install --upgrade pip
- python -m pip install numpy
- mkdir C:\projects\deps
- C:\cygwin\bin\wget -q http://apps.jcns.fz-juelich.de/redmine/attachments/download/456/bornagaindeps_v1.zip -O %temp%\bornagaindeps.zip
- 7z x %temp%\bornagaindeps.zip -oC:\projects\deps > null
- set CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.4-win64-x64.zip"
- appveyor DownloadFile %CMAKE_URL% -FileName %temp%\cmake.zip
- 7z x %temp%\cmake.zip -oC:\projects\deps > nul
- move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
- set PATH=C:\projects\deps\bornagaindeps\lib;C:\projects\deps\cmake\bin;%PATH%

build_script:
- echo "BornAgain build_script" %CD% 
- echo %PATH%
- mkdir build
- cd build
- cmake --version
- cmake -G "Visual Studio 15 2017 Win64" -DBOOST_ROOT=%BOOSTDIR% -DCMAKE_INCLUDE_PATH=C:/projects/deps/bornagaindeps/include ..
- cmake --build . --config Release

test_script:
- echo "BornAgain test_script" %CD% 
- echo %PATH%
- echo %PYTHONPATH%
- echo %PYTHONHOME%
- ps: >-
    ctest -LE Fullcheck --output-on-failure

    if (-not $?) { 

        type Testing/Temporary/LastTest.log

        throw "tests failed" 

    }

on_failure:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#- appveyor PushArtifact Testing/Temporary/LastTest.log
#- appveyor AddTest test

# Uncomment this to debug AppVeyor failures.    
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    
