image: Visual Studio 2015

matrix:
  fast_finish: true

platform:
- x64

# http://www.appveyor.com/docs/installed-software
environment:
  QTDIR: "C:\\Qt\\5.7\\msvc2015"
  PATH: "C:\\Qt\\5.7\\msvc2015\\bin;C:\\opt\\local_x64\\lib;C:\\Python27-x64;%PATH%"

build:
  parallel: true

before_build:
- python -m pip install numpy
- python -m pip install pyyaml
- C:\cygwin\bin\wget -q http://apps.jcns.fz-juelich.de/redmine/attachments/download/279/local_x64.zip -O %temp%\local_x64.zip
- 7z x %temp%\local_x64.zip -oC:\opt > null

build_script:
- mkdir build
- cd build
- cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INCLUDE_PATH=C:/opt/local_x64/include -DCMAKE_LIBRARY_PATH=C:/opt/local_x64/lib ..
- cmake --build . --config Release

test_script:
- ctest
