language: cpp
sudo: required


env:
- BUILD_TYPE=Release

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode7.3

before_install:
- chmod +x .travis/*/*.sh

install:
- .travis/${TRAVIS_OS_NAME}/install.sh

script:
- .travis/${TRAVIS_OS_NAME}/build.sh
- .travis/${TRAVIS_OS_NAME}/test.sh
