language: cpp
sudo: required

services:
- docker

env:
#- BUILD_TYPE=Debug
- BUILD_TYPE=Release

os:
- linux
- osx
  osx_image: xcode7.3

before_install:
- chmod +x .travis/*/*.sh

install:
- .travis/${TRAVIS_OS_NAME}/install.sh

script:
- .travis/${TRAVIS_OS_NAME}/build.sh
- .travis/${TRAVIS_OS_NAME}/test.sh
